# Generated by Django 3.2 on 2023-10-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(choices=[(1, 'okx')], default=1, verbose_name='交易所')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('flag', models.IntegerField(choices=[(1, 'okx')], default=0, verbose_name='API类型')),
                ('passPhrase', models.CharField(max_length=64, verbose_name='密码')),
                ('api_key', models.CharField(max_length=64, verbose_name='APIKEY')),
                ('secret_key', models.CharField(max_length=64, verbose_name='SECRETKEY')),
                ('status', models.IntegerField(choices=[(1, '激活'), (2, '禁用')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_platform', models.IntegerField(choices=[(1, 'okx')], default=1, verbose_name='交易所')),
                ('uniqueName', models.CharField(max_length=32, verbose_name='交易员交易所ID')),
                ('follow_type', models.IntegerField(choices=[(1, '固定金额')], default=1, verbose_name='跟单模式')),
                ('sums', models.FloatField(default=0.0, verbose_name='单笔跟单金额')),
                ('lever_set', models.IntegerField(choices=[(1, '跟随交易员')], default=1, verbose_name='杠杆设置')),
                ('first_order_set', models.IntegerField(choices=[(1, '交易员新开订单后跟随')], default=1, verbose_name='首单跟单设置')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('token', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='token')),
                ('token_expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='token有效期')),
                ('status', models.IntegerField(choices=[(1, '激活'), (2, '禁用')], default=1, verbose_name='状态')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['username', 'password'], name='idx_name_pwd'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.apiinfo', verbose_name='api'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户'),
        ),
    ]
