# Generated by Django 3.2 on 2024-04-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='reduce_ratio',
            field=models.FloatField(default=0.0, verbose_name='减仓比例'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='role_type',
            field=models.IntegerField(choices=[(1, '带单员'), (2, '普通用户')], default=1, verbose_name='交易员类型'),
        ),
    ]
