# Generated by Django 3.2.9 on 2023-10-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_taskinfo_create_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='flag',
            field=models.IntegerField(choices=[(0, '实盘'), (1, '模拟盘')], default=0, verbose_name='API类型'),
        ),
    ]
