# Generated by Django 3.2 on 2024-04-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240410_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='acctLv',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='账户等级'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='ip',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='level',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='等级'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='perm',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='权限'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='roleType',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='fast_mode',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否极速'),
        ),
    ]
