# Generated by Django 3.2 on 2024-04-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240423_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='uid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='uid'),
        ),
    ]
