# Generated by Django 3.2.9 on 2023-10-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231028_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apiinfo', verbose_name='api'),
        ),
    ]
