# Generated by Django 3.2.9 on 2023-10-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_taskinfo_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
