# Generated by Django 3.2 on 2024-07-04 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apiinfo_uid'),
    ]

    operations = []
