# Generated by Django 3.2.9 on 2023-10-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_taskinfo_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='status',
            field=models.IntegerField(choices=[(1, '跟单进行中'), (2, '跟单结束')], default=1, verbose_name='状态'),
        ),
    ]
