# Generated by Django 3.2.9 on 2023-10-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_taskinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='api_name',
            field=models.CharField(db_index=True, default=1, max_length=32, verbose_name='api备注名'),
            preserve_default=False,
        ),
    ]
