# Generated by Django 3.2 on 2024-07-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240704_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱授权码'),
        ),
        migrations.AddField(
            model_name='notification',
            name='qq',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='notification',
            name='qq_mail',
            field=models.BooleanField(default=False, verbose_name='QQ邮箱'),
        )
    ]
