# Generated by Django 3.2 on 2023-11-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_apiinfo_api_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('platform', models.CharField(db_index=True, max_length=32, verbose_name='交易所')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
