# Generated by Django 3.2 on 2023-11-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='status',
            field=models.IntegerField(choices=[(1, '空闲'), (2, '使用中')], default=1, verbose_name='状态'),
        ),
    ]
