# Generated by Django 3.2 on 2023-11-26 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_apiinfo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='代理用户名')),
                ('password', models.CharField(max_length=64, verbose_name='代理密码')),
                ('countryName', models.CharField(max_length=32, verbose_name='地区')),
                ('countdown', models.FloatField(default=0, verbose_name='有效期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户')),
            ],
        ),
    ]
