# Generated by Django 3.2 on 2023-11-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ipinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipinfo',
            name='countdown',
            field=models.FloatField(default=30, verbose_name='有效期'),
        ),
    ]
