# Generated by Django 3.2 on 2023-11-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ipinfo_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipinfo',
            name='countryName',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='地区'),
        ),
    ]
