# Generated by Django 3.2 on 2023-12-12 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_ipinfo_countryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '进行中'), (2, '结束')], default=1, verbose_name='交易状态')),
                ('instId', models.CharField(max_length=16, verbose_name='交易品种')),
                ('cTime', models.BigIntegerField(default=0, verbose_name='开仓时间')),
                ('uTime', models.BigIntegerField(default=0, verbose_name='平仓时间')),
                ('openAvgPx', models.FloatField(default=0, verbose_name='开仓均价')),
                ('closeAvgPx', models.FloatField(default=0, verbose_name='平仓均价')),
                ('pnl', models.FloatField(default=0, verbose_name='收益')),
                ('pnlRatio', models.FloatField(default=0, verbose_name='收益率')),
                ('lever', models.CharField(default='0', max_length=6, verbose_name='杠杆')),
                ('mgnMode', models.CharField(default='cross', max_length=10, verbose_name='保证金模式')),
                ('posSide', models.CharField(max_length=10, verbose_name='持仓方向')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apiinfo', verbose_name='api')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taskinfo', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.AddIndex(
            model_name='orderinfo',
            index=models.Index(fields=['user', 'task'], name='idx_user_task'),
        ),
    ]
