# Generated by Django 3.2 on 2023-12-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20231212_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='cTime',
            field=models.BigIntegerField(default=int, verbose_name='开仓时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='uTime',
            field=models.BigIntegerField(default=int, verbose_name='平仓时间'),
        ),
    ]
