# Generated by Django 3.2 on 2023-12-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20231212_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='uTime',
            field=models.BigIntegerField(blank=True, default=int, null=True, verbose_name='平仓时间'),
        ),
    ]
