# Generated by Django 3.2 on 2023-12-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_orderinfo_utime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='closeAvgPx',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='平仓均价'),
        ),
    ]
