# Generated by Django 3.2 on 2023-12-12 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_orderinfo_closeavgpx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.apiinfo', verbose_name='api'),
        ),
    ]
