# Generated by Django 3.2 on 2023-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_orderinfo_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='pnl',
            field=models.FloatField(default=0, verbose_name='跟单收益'),
        ),
    ]
