# Generated by Django 3.2 on 2023-12-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_taskinfo_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='imr',
            field=models.FloatField(default=0, verbose_name='持仓量'),
        ),
    ]
