# Generated by Django 3.2 on 2023-12-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_orderinfo_imr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='imr',
            field=models.FloatField(default=0, verbose_name='保证金'),
        ),
    ]
