# Generated by Django 3.2 on 2023-12-18 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_orderinfo_imr'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt', models.FloatField(default=0, verbose_name='可用余额')),
                ('btc', models.FloatField(default=0, verbose_name='结余额')),
                ('eth', models.FloatField(default=0, verbose_name='结余额')),
                ('pnl', models.FloatField(default=0, verbose_name='累计收益')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apiinfo', verbose_name='api')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_flag', to='api.apiinfo', verbose_name='API类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='RedeemCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='兑换码')),
                ('status', models.IntegerField(choices=[(1, '未使用'), (2, '已使用')], default=1, verbose_name='可用状态')),
                ('value', models.FloatField(default=0, verbose_name='兑换金额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='QuotaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnl', models.FloatField(default=0, verbose_name='累计收益')),
                ('quota', models.FloatField(default=0, verbose_name='可用额度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户')),
            ],
        ),
    ]
