# Generated by Django 3.2 on 2023-12-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_quotainfo_redeemcodes_userbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='btc',
            field=models.FloatField(default=0, verbose_name='btc'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='eth',
            field=models.FloatField(default=0, verbose_name='eth'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='usdt',
            field=models.FloatField(default=0, verbose_name='usdt'),
        ),
    ]
