# Generated by Django 3.2 on 2023-12-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20231218_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pnl',
            field=models.FloatField(default=0, verbose_name='累计收益'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='quota',
            field=models.FloatField(default=0, verbose_name='可用额度'),
        ),
        migrations.DeleteModel(
            name='QuotaInfo',
        ),
    ]
