# Generated by Django 3.2 on 2023-12-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20231218_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='pnl',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='quota',
        ),
        migrations.CreateModel(
            name='QuotaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnl_0', models.FloatField(default=0, verbose_name='实盘累计收益')),
                ('upl_0', models.FloatField(default=0, verbose_name='实盘未实现收益')),
                ('pnl_1', models.FloatField(default=0, verbose_name='模拟盘累计收益')),
                ('upl_1', models.FloatField(default=0, verbose_name='模拟盘未实现收益')),
                ('quota', models.FloatField(default=100, verbose_name='剩余盈利额度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户')),
            ],
        ),
    ]
