# Generated by Django 3.2 on 2023-12-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20231218_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='btc',
            field=models.FloatField(default=0, verbose_name='btc'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='eth',
            field=models.FloatField(default=0, verbose_name='eth'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='pnl',
            field=models.FloatField(default=0, verbose_name='累计收益'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='usdt',
            field=models.FloatField(default=0, verbose_name='usdt'),
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
