# Generated by Django 3.2 on 2023-12-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20231219_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotainfo',
            name='quota',
        ),
        migrations.AddField(
            model_name='quotainfo',
            name='quota_0',
            field=models.FloatField(default=100, verbose_name='实盘剩余盈利额度'),
        ),
        migrations.AddField(
            model_name='quotainfo',
            name='quota_1',
            field=models.FloatField(default=100, verbose_name='模拟盘剩余盈利额度'),
        ),
    ]
