# Generated by Django 3.2 on 2023-12-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20231220_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinfo',
            name='upl',
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='upl',
            field=models.FloatField(default=0, verbose_name='未实现跟单收益'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='pnl',
            field=models.FloatField(default=0, verbose_name='已实现跟单收益'),
        ),
    ]
