# Generated by Django 3.2 on 2023-12-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20231220_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemcodes',
            name='status',
            field=models.IntegerField(choices=[(1, '未使用'), (2, '已使用')], default=2, verbose_name='可用状态'),
        ),
    ]
