# Generated by Django 3.2 on 2023-12-21 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_redeemcodes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemcodes',
            name='code',
            field=models.CharField(db_index=True, max_length=64, verbose_name='兑换码'),
        ),
        migrations.AlterField(
            model_name='redeemcodes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户'),
        ),
    ]
