# Generated by Django 3.2 on 2023-12-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20231221_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemcodes',
            name='verification_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='兑换码验证时间'),
        ),
    ]
