# Generated by Django 3.2 on 2023-12-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_redeemcodes_verification_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemcodes',
            name='verification_datetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='兑换码验证时间'),
        ),
    ]
