# Generated by Django 3.2 on 2024-01-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_redeemcodes_verification_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='instId',
            field=models.CharField(max_length=32, verbose_name='交易品种'),
        ),
    ]
