# Generated by Django 3.2 on 2024-01-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_orderinfo_instid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='upl',
            field=models.FloatField(default=0, verbose_name='未实现收益'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='uplRatio',
            field=models.FloatField(default=0, verbose_name='未实现收益率'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pnl',
            field=models.FloatField(default=0, verbose_name='已实现收益'),
        ),
    ]
