# Generated by Django 3.2 on 2024-03-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20240111_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('task_id', models.IntegerField(db_index=True, verbose_name='任务ID')),
                ('date', models.DateTimeField(verbose_name='日志时间戳')),
                ('color', models.CharField(max_length=255, verbose_name='日志级别')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(verbose_name='日志信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '爬虫日志',
                'verbose_name_plural': '爬虫日志',
            },
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('task_id', models.IntegerField(db_index=True, verbose_name='任务ID')),
                ('date', models.DateTimeField(verbose_name='日志时间戳')),
                ('color', models.CharField(max_length=255, verbose_name='日志级别')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(verbose_name='日志信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '交易日志',
                'verbose_name_plural': '交易日志',
            },
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='leverage',
            field=models.IntegerField(default=1, verbose_name='杠杆倍数'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='mgn_mode',
            field=models.CharField(choices=[('full', '全仓'), ('isolated', '逐仓')], default='full', max_length=10, verbose_name='保证金模式'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='posSide_set',
            field=models.IntegerField(default=1, verbose_name='反向跟单'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='lever_set',
            field=models.IntegerField(choices=[(1, '跟随交易员'), (2, '自定义杠杆')], default=1, verbose_name='杠杆设置'),
        ),
    ]
